DELETE http://localhost:3001/selected-muscle-groups/3
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NDY1OTQsImlhdCI6MTcwMDY0NjUzNCwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjQ2NTI0LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.B72-H0bBjTx9D2rIcSbHD6Qp4efeiAPKHo0RowxEjBJ61LG2aCM3dMU9W63fUrlN3CVZyeqtzgLRNR8NjF5cx2hHD-FzDMDy3-QESVha23IclHljKdRXjRS_6XcbmE8lLZH6PDFVvhKPq_57vP6dsVXQpHAWCxkd3Ai7p9UDWgFycxXawdVWiDTl48lZ59hLeHYhztz3GNCOTFcvMakinuJvsvEVbbisImRrKYlEplpKSGcpvLbh_savtR50CJByh-WfYoycEhSicRxHGmdgvNTBPFsdDmN562cVZ5wpE3l-P0xdc8pArd11F2kvmRQ8yiJW0rYsE1rD_i7ndXz0hw