GET http://localhost:3001/workout-cycles/8/selected-muscle-groups
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NDY1NjAsImlhdCI6MTcwMDY0NjUwMCwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjQ2NDkwLCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.cgdHc4IX3iXHOFIEimJrmLHKyz2WKtsiZ3Mxtr9ON7CAakq0a72zMWhuL0nlLBm32LPqUqoVOLzU7kCjORdNE_31hcUt_H9poeeHSNZ-9UCTvp9_-sghO-H3J2WApf9umic9oOG_SXxH5ezU3Yce5mBwT5vcjugn-J0wfW_PFBMMhP036H2YWfDu6nJxIKjVdZ2eLx-9SOJy7W2D4EMM6P-4FFz9yflryOYedTA2Wl0EJvWpa9yQzSchmXyYo3CODG9HONchp532b2hSBjlIrQNw91s24gVv7WyY_EvgRi0uT-dYhUW_CmKDxQBobY12Y4TzeXc2w3nokLMTGfLWvQ