POST http://localhost:3001/workout-cycles/8/selected-muscle-groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NDYxNzcsImlhdCI6MTcwMDY0NjExNywiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjQ2MTA3LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.ReC6Hw8STU6hM0-dGZe-NHDK6MN8g69EXOlVjMcQR2_R-71-Wkh3YclxBbmArtSGzS86_7b-6Zx5CXRH3JUa7LZFUnW8oJX9YjYKGf4j-FaeHVGDkssxMy0WtWzn1WfJhyqwqCfHDZY5fHeVxnjhn5-Ja2ucx471Ux9LjVFGkkNX0Sy9QC3VnaNLxnR6pq3ZH5WMAdgZ6a0-KQrFppuT5zpFUmPGNPyb9wZ9jbj5UKUHw-JtB5DaKc_55P-Q2_2lGECC559LK81AoVqRE2Z_jHcGNNKaf3O3t8w9q5S5WhY7Ax7k_EITPbm76VRQ1_m6C5AR8o2y3UWX0agaSyljcw

{
    "muscle_group_id": "6",
    "is_priority": true
}