PUT http://localhost:3001/selected-muscle-groups/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NDY1MDAsImlhdCI6MTcwMDY0NjQ0MCwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjQ2NDMwLCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.CUWK19V-f03HY6vrkRTQggcHHmkgK3l78ARIn2SQkLKHJoqSFGCA7RC7hWMn8Fm9H3c8b3gZfroyNTVDc6pFJsCR2LpVNCwtlynB3EjLhN3j_Llyuue9e63Sb61-uTJlwMms75FzvJDrGaKiSBstNbRLfoHIQyeKIyt9AZtSBJ5xcP92cNNDeAnn592UFYqOHclv4J7inklDrdOyNf95_Bos7-kaFESDkEQp530OsCYbbtln5JfjA0uvA7NNdkuzH2yBmtQY6wTkLlzlatR00M8k95g6uBVP4338SCminG5qBZzyG5DJ8wut8IZYKvRTAoAZg6a7N3dNTIucd-Alqw

{
  "is_priority": false
}