DELETE http://localhost:3001/users/user_2Wtl6nOCJyyfUWDGkrGTPCAsGdZ
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA5NDIzOTMsImlhdCI6MTcwMDk0MjMzMywiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwOTQyMzIzLCJzaWQiOiJzZXNzXzJZZ0w2ZDlzV2xDNEVuNTR4STZsTnhqQWtzciIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.KcIxUTQvn9yXX4cYHwtRHIymZpqohfS15Z3cc3Xl0b0nf_tiXkabsJx16r8oHbQJ3W6gtDPux7AXx2bV33-i62wQ9nw3vR5r7A2j0sR1zvPwbrTSx40KSeyMJYlkayWMlTJHthZRO4p7-nxsMxj_52e-X5b3qnPUqI5LXg6YHhKlYQ-rj53KY1g9C-w90nuzmz_rqAVN_7jgHjPsn665n_hs_HPbiQdPdhngMKyopZ7cvx7iRYR5cXJUMZOI5u5e-6UcamgULx6oilhPqE6kPQ3jwa5l3N8_5BHupbqy5zuSC3l-wbMuH2j6Ki8JdLpAByZ07rJnnnRu6IgtI3zEVg