
GET http://localhost:3001/workout-cycles/8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTI0MDUsImlhdCI6MTcwMDY1MjM0NSwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjUyMzM1LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.Hxnfky3NK0DvgGF2a0Jtg_c3MWH-SOL1ywXgUZsqzVNIwQ8q4pi91J7TirGezqTqx0k5FssPujBYgClnrrrdE6qtlTjYrzGqNLFWYI0J9z703dUenm6co9GvfZBtqhT95CS_pHT0WOEeM6VTYuXrfF0l_S65sxLKzNmOYz79vPbj50zInXLCJ9QJlHOXXLsFng9LNG6sUetbLRwlrmuTLAMke9fIfgOZ-1YZmpVbSQtmnPVnocdUAoOzsrDc25Pn9RtYBEsW2Zox8YxN-6p3xBWf6ZPQN3bqtXIDmM_slKUu_q8jcV9NFT4knPVxEd1fyEa2pRsEeXl5nJN78cQpFw