GET http://localhost:3001/workout-cycles/8/volume-feedback
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTA2MjEsImlhdCI6MTcwMDY1MDU2MSwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjUwNTUxLCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.lZYlnrHbC0NFiY04kEMLWSiu6a-6hoe-BUsOIrlGYm38hX4sN9H3jFEu41JGDi7U1kqIUMeVKvCdEh-H7JEImld55gq-LHlgoQfFHVrH2PRQ5gCpw3LZ8RAt832HtELTYXAkfox36Iw_VXsM4XHRqIfKLz3TfxFI6sT_kelQTO68dUfYXtFb2bZBXzwsnw9RWSB7gYqcrJi826MjnlbCwIGKbq8jeUlAfsVz9OQdHkclCBs25OVxu6TRkSyWR8ulonqbv8wXVKA0iw-CIpT30Iu8HDXsiACJPuaJbBZmiNP-BoNAHcC8ThvbSC1OGd2XEIbrTvwwxoKhfDLO-DJqRw