
GET http://localhost:3001/workout-cycles/8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTY2MDUsImlhdCI6MTcwMDY1NjU0NSwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjU2NTM1LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.RW17_ZAjPZID92HbExLbTv2tWhA1yFU5IGzuuL5RrdP8bOihpVl0DNMOhSZ_u38s5dZZJH6SWkuxNKvOGhYp69dW3ekjanA5CNC0tm_LGUxy5wqQ1x95HsCLY2c8U1YrSABoyjP6wBC68Wp3p1ntXggAASKdbWhEKkHhux5GVHslCsv4vybedQgBAEFkcnNiYlYOVMeiIgYP94mI8L9_7Tz_7y521zRkGozGZs_Ij0l7eZwiHlUySUsBMUB_mx5lMOWoNKBPBNcGccFLQBlGT1crruY58c4kjCBsr2SGay2sdQgZTwgkMoQ1toE_4lwNv3ODuFP1RLyl-E7P3jZfHg