GET http://localhost:3001/users/user_2XLaZEc93ULD95U6y7OK5AI8oNv/workout-cycle
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTcwODUsImlhdCI6MTcwMDY1NzAyNSwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjU3MDE1LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.YETTnP9n8v2CduklkYbdTt19RrahW-U2XlKH53-9hx6yDyWAZRjoK9VCRrxpMbrKW5lMV8ffBC9hr5YSvOnOO-M2E1Ts14wH6YqyderAKaIDCHoWqBUFxYalKiyD7WAzGqD3PObSGLw7KocERcX0bALBLiSKtVbXGhHfBBp6Q0IPyY2DTRjs23elMeLDOpTzJMdR-mZz5AOA62X4XmQ5obpdoaOFd6r7YSYXmAC33Jg5HLlIOjMh-jNJa5wamMPSG2hmbfjSblzhqVwkRJMkGht1E11E7eRTbJPxs55_BHd_3EUc469K31qJiGyfQOP_iha05Gv3052J5OCkRVSFEw