GET http://localhost:3001/workout-cycles/8/musclegroup-rest-feedback
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTY4OTYsImlhdCI6MTcwMDY1NjgzNiwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjU2ODI2LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.G1Qa7xRTriLAwnjTLV8mJRZAa6mxiHme6O9iIpigkK-bMXwGQy_nx543twBicz-sKzoOfteqTYITJdj_wL_R4nGPVZMB18xrAK30ILnXIWwAnCyMCLfi3rGRqV6K-mLzhocuXfSghU5O4ZSFf46Ooiz5a7lzi1-VMNhKc5Hz_YtkdHcKg_fciPbp3-MwvibfMrAaut9mmNoAM4d4mb7zB5UM87916mNqQOTfn6VOzkTRUmvOO4bzFKczW5sRF1A63jaqeJwFLjsVwMssNN6f-6XyVmE1-IH-imjFU_6TMDLPMiiAlYre0EW80YLuitJIiINtsX3wj7DMe6u2q2Hczg