GET http://localhost:3001/workout-cycles/8/volume-feedback
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTY4MTYsImlhdCI6MTcwMDY1Njc1NiwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjU2NzQ2LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.OWMeFBNwfcsWievfUUPTYp_NpWc5jljVxmOiN2iRbDxEDCzHFViSU8CYNQN8aHuWm2eoZS-xcnP4CWu28Et_gPInXIcuDkbGfdP4LQJqzSR9R5wThjPInHz_0Ja_ejarFE1ZqJDHC2aBHTqtwBKn1DepgR15kCFetOeJjopG13HAlO3AbzJDGiWmMrJlZgA5LGDD_oqov_W-SoAGe5HQyEUil-wVUgkuoIoC3lVtZxwhcwRpuUvyTCqpw30ZKH6tieoTSpcUz7g5w_oQ3gPCveN0sTxVctFRIooGflR2i4DNDhxoXGd13JxjZmmyv9EMqDgqUruhJsEE29uHyfxHtA