
GET http://localhost:3001/workout-cycles/8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTA3MzksImlhdCI6MTcwMDY1MDY3OSwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjUwNjY5LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.Ej14yz4LNSUjLmLnjMmFptWIyh_VmY_Mr48VbFryph1w0reypPZnRvpL2lhtBhp46FVLjPcLQy4EPj94ho5cNjy9DnAr225VVmJAzWTi7x5_TyTZpxRlEy5jzL7TQoAdD8AFkOJf6HDleouA701-xNmrGIusWgK8Td-Ik071uCxU7KZOHnbAzrzMPQsNuK39rjCsNyjbTbUqx_mHUTl5SzvCRmxaVp2mRWVnOx5lZ-0UxB0ztN-gNJrQpDHjmLF0t9ghY7L0C5bULMvuCtRQjXPKNyrDV8ui-1OwQ_ZqKC7cDJAUaCi81_EzYQTQMxR2Hr6locrzsqeaCYaVFnOk1g