PUT http://localhost:3001/training-days/31
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE2OTk2OTk1NjYsImlhdCI6MTY5OTY5OTUwNiwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNjk5Njk5NDk2LCJzaWQiOiJzZXNzXzJYdmVpQ3N0NmFPWHFZYVhuc2V1QU11M05sOCIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.di-5v9feZx-pto8w_Ny2mya1gjU8FRNXexoe6QoqQpQvgkAZM8r4Kl6ykOnfmrFYHGEtpbu0C6K9Xy3VosY8K36xK6obDdn8eS_lYcAc_BZ-c5LQbe-IHoWFfkYyUW0haMtrjDJdOQfiCBAnKJ6r1jyJKL5Yojj721t8_KhQsP8F8ERfB0e6YMeWs96Xiqw2xCDrHo-hXSTLGRLfzpNeyYLu1wef6Cy5n-UZv7dmxqverRkftBLgaLaax8qcXXS1TH2Qk2ar6zxDr68TaXLDyq6-D_00ia_15Nh7R4DmlSJ4HEHf7C0kvl-VEo_xn0RMO04B10ewFz1F2mvAJOkpRw

{
  "is_rest_day": false
}