PUT http://localhost:3001/training-days/35
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTU1ODUsImlhdCI6MTcwMDY1NTUyNSwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjU1NTE1LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.Wbf__7gOsglkP9lAQsFesUKXwzXo23xFo0yCG8gQhAMQKNajr_8v-4qHQ381-QdbHc9hOF50uKpaWX3kGzhorA4K7BjJNbGVOZzcIpjP8L5Dz96rjww5FsItEe77GfsQ4oijlmQMwWgY3NauXY20PwBZB8WEtPaerK8HYmEfkbRm2He3FSPac9lIV_MvQ86Xzo4ynRku1Am2LeOzYH6o2h3S8Bu1wZCJC7Ne2cNYNZeN5POsx9Nrzjvz0ailzYbwAAjbwxzyCi0lqSTnkJVLt3sjyY120DUUZNsOQ9L8keWIE1Dsw2sV_vdIFsOrkBEmQTDvNuw3NB4sa-EQK3SSPg

{
  "is_rest_day": false
}