PUT http://localhost:3001/training-days/34
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTIyNDksImlhdCI6MTcwMDY1MjE4OSwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjUyMTc5LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.X5vC84rsitID7S6ufsUI8x8A-fU4TtujinUmmP9USuF0py4PQlZRlEryutOaEmU5Te6urAUzixyaIWmFK_aTKPQM2fn2OX5doFmbieSDL2E-OIVNX44440l4MJXJfw-mZmGmqV1LpGQeAKNZ6aFNpd2PFpX08Ds8PDmsriVLz0ZhOyA0yM5gEHJ3mAibo3pwTIimYXJHKnAu_fN2IdIBhxBqZ1JOF42rU4GLV9TyVCfnunJ_akGUXDO7tHG_pSAW5Roil9H7F6GuwOb9RzTs31JoIsFZfZhteeUkuvTPt_MfzJ9XFguQjjRElfdZep11Fl9elEn9LOCmCFPhcRHDaQ

{
  "is_rest_day": false
}