DELETE http://localhost:3001/workout-movements/9
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTE3MzMsImlhdCI6MTcwMDY1MTY3MywiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjUxNjYzLCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.Da_Ysz3A2sbPgTnNRNTgxX6P7x1PAEu1-HsYujgZo8vJqmDsyHQuoJ6JtyYKka0XoERMjwjpwD9rjzmgkAvVQP_3qAmsYB7ID5snoxV0mZBR-YyAAqfcdQF2_56yoWI2mnSe80OooOc2563nopEAbY0JxM6EN-goJ1YNh1KFyoiLmsYkVWeJU2MTfbAiTAJ7424D2n30Wfd5bNtZMnzXZbzN59dNjO7Y45DartSpiIQjlZf6K9BB8L2z63NXe-7gnualaUJFJbHdjzGcB9xJ7OCYB4jN2e69FJyKxooSE7-jP5_r2suwG8PLZXcAtfsq1tHZEFQOl4NP0nqvIV-qdg