GET http://localhost:3001/workout-events/1/workout-movements
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE2OTk4MjAzMTgsImlhdCI6MTY5OTgyMDI1OCwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNjk5ODIwMjQ4LCJzaWQiOiJzZXNzXzJZNU5iamc2VFNkTjV0a2JjNzBKdEpETGp5NiIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.eBebsNVLhxTyu4aKtsT3YidVrFVRwGH7ves0ZetZOPFu_H1v8iV6aJdar8XDWXat7tKjcqvb8Q4liXlFQtQsi9Yc91w1_v_X3hGpSyDZ4Zw46KpRgTFE-mrhyVyLHxnFXa4mVvvXvTrIQY9JTO9v9lJvxi4vAkVtuzd-kaM7iJORI5PbSc8OJuEbphR0b-3LWgc_Ko_FA7bRMZz2vab3MrFspP8QQPkIir1DUrwD7CX6x9Q4M2zo8m093uImFGaMSMoTVBxhW2naTixgsdgS-7Ee69PwZ0l1rSctwOvY2pX-hJ7czw9Y4Li89iL6ScRyHXUhO5m9xtj3qTpzCQW2TA