GET http://localhost:3001/workout-events/6/workout-movements
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTY5OTksImlhdCI6MTcwMDY1NjkzOSwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjU2OTI5LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.U3xlLxkUew8Q5-wM7DQOt8jCbTI6cMGBobNUv-QysftIDCF0vQI1S-vZ7xjjlKY3BOqseK-L02jsLjFpI-8eeu-RN3Xc0Ee59vQ5S4dAH9jZTKk0LTgfXP48tQxi4V6mwCPdTr0I9PIr8vDRx4l2mZJ8N3Rsw_jBBM7Uly0I-rDJ6s_watwRI8hsZyyR3_JUbmSLpWe9ckJ-b2OqSNV4Z-dK7mvo3mOqbta2I7SzxF_XDk2LMDli0T5PoodT0pj2NBrALevzObs_vOFRT5CNQ_Q8oyzWelmva53CUUvs0IS6ngTXzsRLqOxkdajgw2Al499KDtEhOXFXULHvKlXo8A