GET http://localhost:3001/workout-events/6/workout-movements
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTMwNzIsImlhdCI6MTcwMDY1MzAxMiwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjUzMDAyLCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.O5ZR4gh5osGDyokeFKAnaQppEkW02ZbhNzP6NYO2p5Py2OuDhe7KnHce-CeKkg1y8RBIJtFwPQycoKUGgKw9d_eeijtinHHqAzc5lcrDw6g29mysmx7_sp2CVmXTdH8H8cFqlhSHaI6CW2z-VCJunqb7kK_E0jEjGYijV9xW52DCbQj8PZt9CcAHkdqy2Tt-Sf8xOWqErktwjocV2uzFGE1olxKruVp2TgYvuZXh5qpyud0AnqBhdZUKMo7uZYTxPc8EqK1H49Z8AzQvocKi-lLZO2KBJJnlnHZ2yZHV4dUftTMlNkW2vX9m0L8Jr90h-GlMtCDlSKtS8uIcu2twIw