POST http://localhost:3001/workout-events/8/workout-movements
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTU2MzMsImlhdCI6MTcwMDY1NTU3MywiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjU1NTYzLCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.i_S_bwauRbmsSTklowqa1Nc6-mAZ6t02d9h1KOlbCwIwQo0QNZUMBSWjmUudzMUtjkoY9a3_U_a7bieyoBZDaqMpICjG1EEJO1P-kFp4zGZmGCZzksFGe3fRrlETVVHXJ5bu3Rt0FC0DpLO6KBMn3CwYoTDnw4nIcC04Nfzw-ZDiRnnbj2k96cVqekDlY0b4wXtZpdrqGRRl4snY0pyh06Fbnftp9h1PO0iDHutqWQ1OtJpB3eBfrXOY4q_1K0wF_E0xshjSwJh1ydOgLBKeOLc1RwYCzwsdnGObI0On4RN4ZEorPUMF-k0mMOFFFY4EKFr1aHX-eX26HbqflS-1oA

{
    "sets" : 3,
    "reps" : 10,
    "movement_id" : 2
    
}
