POST http://localhost:3001/workout-events/7/workout-movements
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTIzMzYsImlhdCI6MTcwMDY1MjI3NiwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjUyMjY2LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.RGk7fewzoUVLxi3kbLaJNqXsbBarOYcJu4CwTvba842JcVH9GVierNrHuLDmAucxqgbWVqOKbWLq0ZQqFPuRbLkHk835RoHlG5TT-gpLBLP_g07X1Tr-LjuIbcSVCevnTjGhcVzhzQMkgROrq8NUG8aYHsvsxV1Vp5Oo8sGaIlRUYndfAPXPN87HqU_WEyPUPC-njwWGbdAtVHntTXBw51ERpf3ZUu9_iaqRxeF9k3481uhHGkyxBDuWWFcCZebs-iJKX8HEbYGv3jNMgR31fGPNXpD8f1erzxG4SRdBfeNu9IXu9pOmzcJ8fzq9iCiVaCkjsHCdgR-ui4jeuKxIDg

{
    "sets" : 3,
    "reps" : 10,
    "movement_id" : 16
    
}
