POST http://localhost:3001/workout-events/1/workout-movements
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE2OTk4MTk4MTQsImlhdCI6MTY5OTgxOTc1NCwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNjk5ODE5NzQ0LCJzaWQiOiJzZXNzXzJZNU5iamc2VFNkTjV0a2JjNzBKdEpETGp5NiIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.hj4Tb4OoE3BAzbxyPwv4o3Q6nPBPfOXFCIxbY59I5dvoEvLxZG93VmuYRbMJDds0Fc0DgLJkdh7wiBVeip-vqMzVG3-uuWawu0gRc0AIDnvPRwIZvuUhsPA-g3f9dzvaATnM1wlFcBL0DtMoH56lcOStRIUO_qGAzY4rELQGjJdABoHaCGq_ATF8n9ZLE5TvFDkX7RYwPaWfGbW9dvbnCs-ssW6cbo2YAQo8T9R0gEKx3UNR6BKcOJDXCcCRqW6YiM-Pk2gU2UMOtZMc66on7piuezYhS6wwg_z40hf87mlGGm2ucKTvuuEbT9yvpsRXAZJVI6SLckfxbyaVawgDEg

{
    "sets" : 4,
    "reps" : 12,
    "movement_id" : 8 
    
}
