PUT http://localhost:3001/workout-movements/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE2OTk4MjAyNDksImlhdCI6MTY5OTgyMDE4OSwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNjk5ODIwMTc5LCJzaWQiOiJzZXNzXzJZNU5iamc2VFNkTjV0a2JjNzBKdEpETGp5NiIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.IRuI3e4b7A0-OwsKxrU9iM0yFhSukOJhGib_ncryS9UH7pqQztQXxDup-YWlv7JPQ1McfS31p3BFbWMQvAmGVl5P8zof_7vDI2Jo6kSIbTfkT63GwFiHC39eivwgom7d0zpe2X2jxnaNetgs5SEammgx0nCbDMgM-7w3cgguUPGmdCleVyr0TTsI_CjtzppASE4YBPh1Xr0isyBurzmVzJSNFYtczHxD-bh7yM65Lz72_0XitxGqH6eLIPKCcBsO9W1D7g0cBMDApqBjdfkMKljXoTSDOFSGWiFexNFSebcCcd_ZubNuU3iv_3SPpRXex9JKo3eOTlNOsS059bTo8g

{
  "sets": 2,
  "reps": 15,
  "movement_id": 9
}