POST http://localhost:3001/training-days/31/workout-events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE2OTk2OTk2NTUsImlhdCI6MTY5OTY5OTU5NSwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNjk5Njk5NTg1LCJzaWQiOiJzZXNzXzJYdmVpQ3N0NmFPWHFZYVhuc2V1QU11M05sOCIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.NZOH6SVhvojPYmSY5hc53JQE--eiiPDBW2yo0N-FFVb2L4zIdXfqitX0EgffIgtefM59Q077vmnFajb_qxZGjV6jTul2TfoLKZ9zS-4uXbTJFVd1x1c7IsNIf7fDxEZ-qU7gAh0Ni4_me9_P_JuvCTP44PfvxjBcf5kmaQxlxrLP-5rg1EMcTUQkU5eQxO8VeUZVpdFEByPOvjA33XYRWU2XSaXoXB1u54QKrILAARMJqjPEBcRQC6bl742mcqsGKd25T4f-HYkhQ61y9-FaZs9oPjH3bXBpfve4Eri-JKnuLs-buU2nwCyOVDJtxZnHulI57nRwLWrjzUTxFZx3PQ

{
    "name" : "Workout for day_id 31",
    "order_in_day" : 1
}
