POST http://localhost:3001/training-days/35/workout-events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTU2MDgsImlhdCI6MTcwMDY1NTU0OCwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjU1NTM4LCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.HARsw8mCc6f-jjhgHUMt6K0cSOIJRzpFiNaRoJU0H0A2WRQS9Crh_2zFotjeVBKWe_v-tlUUOTx4exapKxMdL5xlGbCHQu7jEzzUOAahHu2XpojT2x0b827HyEI-Er06FZkgjRGfOC7OfMqQG_rWDEREi8qmQpusm9zAlTO5OE5ljQ0dhBxuyHcBhvoCWPaU4O_W6AYjaI1sQ8dlziCmFJYC55i4-FrcOSgNdCU1FKIodknNxFM4UbQXcMKbS35KxlIPzX0j-r1rAO_zXqAkhupOERPeVAtAbQqbkDu_MH4TQIhUm7xvU-DZKLSBqtCQQepUnUfS0wwcko31QnNBuA

{
    "name" : "Workout for day_id 35",
    "order_in_day" : 1
}
