
PUT http://localhost:3001/workout-events/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE2OTk2OTk4NTksImlhdCI6MTY5OTY5OTc5OSwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNjk5Njk5Nzg5LCJzaWQiOiJzZXNzXzJYdmVpQ3N0NmFPWHFZYVhuc2V1QU11M05sOCIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.LlEAiPTtPz8eOn6qUO0sD1NbxDeWR-HMbSBS3V7jO9z4laUPpzNUGT5wmi4zIhqlJkgj3O0Vtvyjy29gfvydYVT03QoAFQl1CKi6xbgKjwSdjVsJl9AYIDAsQMZo18F-NbpwRQ1ZYB6_958kBK9S-116xRzihhwy_eYWKr4A3vS94aBR2dkc2QIHcQNjlzo32HkrOysGxVDyn64_DhHJmu-sQj_VpwOZnW4pGN1I9CyrvEtUrNUem8NMLMP6nEfoMEFRyYVKJWK_-XEptMxFp8O0pJ8m34lIhTbxB72Ani_Au1FYVePM7Uzq9LH_El_AkHUJcjwTnlOz3cqu49wa5Q

{
  "name": "Workout for day_id 30 ",
  "order_in_day": 1
}



