POST http://localhost:3001/movements
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDA2NTE5MDAsImlhdCI6MTcwMDY1MTg0MCwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzAwNjUxODMwLCJzaWQiOiJzZXNzXzJZV1lKVTlRR2VSRFVpZldXU3F4Q0plWmR4dyIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.b21n6Ql7ZNAxuVPnxZhaD5_Uj4GdpIZ_s7RJ0vq1dE8XPDmQtHjnRLIuSdi4gKRykCsEgChqyALqYOsHPr4ysVj2mHWottwBOavQnTPAwKjimThgshRi54sBHN4XjFhwT2co4TDsFqBuo_TyUAbPrN5EJMcbGGem_PoQCY-i8OPgnbUUf5Tf5XtOhedUc6IleAhsyTx9NcUlofYyL51-nMNpYel9hkIuSb8TvGbz-NCGOvJCkQbwdvtk2GvC0GQSflsSQjmnbJ_3lxjT203XYHv_2GxyNQ65btPr3W_-Rtq687J5yfdDYVgCOwKaXkk6FOgdWI4JgJgQRUiuabPqSg

{
    "name" : "Incline dumbbell bench press",
    "description" : "",
    "muscle_group_id": "2"
}