POST http://localhost:3001/movements
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE2OTk4MTI4ODQsImlhdCI6MTY5OTgxMjgyNCwiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNjk5ODEyODE0LCJzaWQiOiJzZXNzXzJZNU5iamc2VFNkTjV0a2JjNzBKdEpETGp5NiIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.U-ql7xYgLW6J3afJXyrfoYj79zyihJ4OXAgrzrpec5pdvpqQiz02QOyaUl51b1mBl5A9-dLyevabI0qRG2N5FkTCzXnFOkzbpOG79nDN_qz_1q8R6XfRfXv8huw3gNglsMUdaEs8LzrB1F2qBNXAmxTcetrMxow9xgkoyJ4SLWw0XsjwIhcYXF6VSUmHN14ymHhqJFnp9_-6Hr6GU3btWY3kV1Hp939hmuzCuJJtJwpszoW1XHtudcQ7JhLdD-ZzdM7tJvNFZ3eTvGWfa-dioPIM6hOOYatDKw6AIHxNe2wxKbS8z7-DQFy2O5FOuVc6rIdAnY7PPwX6U7GRTUXkAA

{
    "name" : "Cable crunch",
    "description" : "",
    "muscle_group_id": "10"
}