
PUT http://localhost:3001/movements/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yV3RCOHhKMlFTRHBBOGJuV0Jxd1FXd3c2VmwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE2OTk4MTMyNjMsImlhdCI6MTY5OTgxMzIwMywiaXNzIjoiaHR0cHM6Ly91bHRpbWF0ZS1nbGlkZXItNDcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNjk5ODEzMTkzLCJzaWQiOiJzZXNzXzJZNU5iamc2VFNkTjV0a2JjNzBKdEpETGp5NiIsInN1YiI6InVzZXJfMld0bDZuT0NKeXlmVVdER2tyR1RQQ0FzR2RaIn0.KHqK7GVMiIn9ntU6MAdU0MtWuC7XSlc0sho3PFxViDHc6kZJG_d_BcUG62HasHEL-dLlBtTbNpPiDX4koU-jwv5wRVcOhOJho33igddeyu2N5fdycZE8xX5bs86U49dYjZXV2rOBhsoTRW05RjQAizUPaPzhHqdWgR5WyuqgpMecHRC9DczcWKaWkFx16CAIUuJK2JVQ4BZyxyYGB_95tQj9XwhFJNbI5Bmijg0uo-IUZbxOYnPTc2LTcww-uVckbzn3C2CDlDjWoCnG1ewq_GEYtXF9TMBQn5MA-d2R17JYeKshXgt4WYLS1iLxpyRSIAF2fgQlHMl83cI1jhJqkA

{
  "name": "Romanian deadlift",
  "muscle_group_id": 6
}